### PR TITLE
CI builds should use 10.12 as min macOS version

### PR DESCRIPTION
**Pull request by ChronicallySerious**
Testing a fix for #119 

(I don't have a mac 10.x system to test this on, so any help with that will be much appreciated!

### CODE REVIEW

**Comment by Calinou** [comment]
> (I don't have a mac 10.x system to test this on, so any help with that will be much appreciated!

cc @daviewales

**Comment by daviewales** [comment]
This is improved. `otool -l` lists the following:

```
Load command 8
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.13
      sdk 12.1
```

However, actually running it gives a missing symbol:

```
Loading resource: res://addons/godot-git-plugin/git_api.gdns
Loading resource: res://addons/godot-git-plugin/git_api.gdnlib
ERROR: Can't open dynamic library: ~/project/addons/godot-git-plugin/osx/libgitapi.dylib, error: dlopen(~/project/addons/godot-git-plugin/osx/libgitapi.dylib, 2): Symbol not found: ____chkstk_darwin
  Referenced from: ~/project/addons/godot-git-plugin/osx/libgitapi.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in ~/project/addons/godot-git-plugin/osx/libgitapi.dylib.
   at: open_dynamic_library (platform/osx/os_osx.mm:1956)
ERROR: No valid library handle, can't get symbol from GDNative object
   at: get_symbol (modules/gdnative/gdnative.cpp:510)
ERROR: No nativescript_init in "res://addons/godot-git-plugin/osx/libgitapi.dylib" found
   at: init_library (modules/gdnative/nativescript/nativescript.cpp:1503)
```

I think this symbol was added in 10.14 or 10.15. I'm guessing that something's missed the min_macosx memo. I'll have another look through how it's built, but I'm wondering if it might be related to the dependencies installed with `brew`?

**Comment by ChronicallySerious** [comment]
I think it's one of the libraries built in `build_universal_openssl_libs.sh` that didn't pick up the min macOS flag because technically it was built outside SCons. If I look in the script, I don't see any flag related to that being sent in.

Need to see what flags does the /Configure command support when building OpenSSL and then send that in if it supports setting a min macOS version

**Comment by daviewales** [comment]
That was my next guess. I'll have a play.

**Comment by ChronicallySerious** [comment]
@daviewales I made a couple of changes in that script and we got new artefacts ready here - https://github.com/godotengine/godot-git-plugin/actions/runs/2819308657

Could you please test this artefact again? It should support macOS >=10.13. We couldn't do 10.12 because of some usages of `futimens()` (added in 10.13) in the libgit2 dependency.

**Review by daviewales — APPROVED** [review]
It works!!! Confirmed on macOS 10.13.6.

**Comment by ChronicallySerious** [comment]
Awesome! Thanks a ton for testing these builds!

**Pull request merged**
