### PR TITLE
Add macOS ARM64 (Apple Silicon) support.

### PR DESCRIPTION
**Pull request by bruvzg**

### CODE REVIEW

**Comment by connorshea** [comment]
FWIW I'm using the dylib linked in the description on my M1 MacBook Pro and everything seems to be working correctly from what I've tested so far.

**Comment by connorshea** [comment]
And it looks like the godot-cpp repo has a PR that's been merged to add ARM support on macOS now? (different from the PR linked in this one's description)

**Comment by bruvzg** [comment]
>And it looks like the godot-cpp repo has a PR that's been merged to add ARM support on macOS now? (different from the PR linked in this one's description)

It is, but without https://github.com/godotengine/godot-cpp/pull/587, there's no way to build both architectures without an extra hack (copying godot-cpp files around, to avoid it overwriting it). Also, it will need extra `lipo` call, since merged PR do not have support for universal builds.

**Comment by Calinou** [comment]
Should this PR be merged now? We can run the `lipo` step manually on CI to create an universal library.

**Comment by ChronicallySerious** [comment]
The scons option names added in https://github.com/godotengine/godot-cpp/pull/584/files seem to be different than the ones mentioned in this PR, but it doesn't seem hard to port these changes to suit the changes that were finally merged into godot-cpp because thanks to this PR we know where we need the architecture changes

**Comment by bruvzg** [comment]
Updated to the last `godot-cpp` changes, now it should work.
Fresh binary for testeing: [libgitapi.dylib.zip](https://github.com/godotengine/godot-git-plugin/files/7241173/libgitapi.dylib.zip)

**Comment by ChronicallySerious** [comment]
The current build failure in mac just seems to be related to using the build config argument that goes into build_libs_mac.sh. I guess it just needs to use $1 instead `release` or `debug` in the file path. 

There is a catch here that $1 is documented to be `Release` or `Debug` instead of their lowercase counterparts

**Review by ChronicallySerious — APPROVED** [review]
Thanks a lot! I didn't have an M1 system but since people have already tested the builds, this helps a ton!

**Pull request merged**
