### PR TITLE
Update build process to suit godot-cpp in >=4.0

### PR DESCRIPTION
**Pull request by twaritwaikar**
These changes should at least build godot-cpp. The plugin itself is still facing issues

### CODE REVIEW

**Comment by twaritwaikar** [comment]
CC @lalomartins

**Comment by twaritwaikar** [comment]
I have been using these commands locally for now:
```
cd godot
.\bin\godot.windows.editor.x86_64.console.exe --headless --dump-gdextension-interface --dump-extension-api
cd ../godot-git-plugin
scons platform=windows target=editor godot_cpp=yes generate_bindings=yes dev_build=yes gdextension_dir="../../godot/" -j 6
```

**Comment by lalomartins** [comment]
I guess this is obsoleted by #132? Or do we keep it around just in case until the other one is merged?

**Comment by twaritwaikar** [comment]
Let's close this one. I only created this branch to push the changes I had on my side to remote and the work by Fales is much cleaner than whatever I did here :)

**Pull request closed without merging**
