### PR TITLE
Updates for issue #150 to use UTF8 instead of String when dealing with data from the git repository

### PR DESCRIPTION
**Pull request by markeel**
Re-implemented the original update for UTF-8 based on latest master, for a clean merge.

Replaced the places where the libgit2 API used godot::String with godot::String::utf8

Tested using emojis as place holders for language specific Unicode characters
- in file names and directory names. 
- renames of files
- commit messages

___

- *Production edit: This closes https://github.com/godotengine/godot-git-plugin/issues/150.*

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Looks good to me (I haven't tested it though).

**Comment by markeel** [comment]
Great, what does it take to release it into the asset library?

**Review by bruvzg — COMMENTED** [review]
The following places probably should have UTF-8 conversion as well:

Old path:
https://github.com/godotengine/godot-git-plugin/blob/2dc9e61f6ca83befaa56839b81ebd8c2340da285/godot-git-plugin/src/git_plugin.cpp#L249

Both "name" here:
https://github.com/godotengine/godot-git-plugin/blob/2dc9e61f6ca83befaa56839b81ebd8c2340da285/godot-git-plugin/src/git_plugin.cpp#L276-L278

"name" here:
https://github.com/godotengine/godot-git-plugin/blob/2dc9e61f6ca83befaa56839b81ebd8c2340da285/godot-git-plugin/src/git_plugin.cpp#L388

**Review by bruvzg — COMMENTED** [review]
And few more:

Return value:
https://github.com/godotengine/godot-git-plugin/blob/2dc9e61f6ca83befaa56839b81ebd8c2340da285/godot-git-plugin/src/git_plugin.cpp#L355

Remotes:
https://github.com/godotengine/godot-git-plugin/blob/2dc9e61f6ca83befaa56839b81ebd8c2340da285/godot-git-plugin/src/git_plugin.cpp#L364

Bunch of `godot::String(...)` uses in `git_callbacks.cpp`

Username:
https://github.com/godotengine/godot-git-plugin/blob/2dc9e61f6ca83befaa56839b81ebd8c2340da285/godot-git-plugin/src/git_callbacks.cpp#L83

**Comment by Calinou** [comment]
@markeel Can you make the requested changes? I'll merge this afterwards.

**Comment by markeel** [comment]
Yes, I'll take a look at it tomorrow morning.

**Comment by markeel** [comment]
I incorporated the items @bruvzg  identified in his review.  Those were subtle impacts.  The only change I didn't apply was the one in git_callbacks related to username.  The trickiness with this fix, is whether the string was already a "godot" string.  In the case of the username it was coming from credentials and therefore was a "godot" string.  When it comes from the URL the string cannot be UTF-8 since those are invalid characters in a URL.

During testing (where I created repositories and branch names with emojis in the name) I ran into problems where the messages being logged to the "Output" window using the UtilityFunction::print(...) methods needed to be updated.  Many of the calls were converting from a "godot" string back to a CString, but then the print function would convert it back to a "godot" string but not convert the C string as a UTF-8.  Since the print() method takes godot string it was more accurate and effective to remove this extraneous conversion to CString.

I also tested error legs, but shutting down the server running my remote repositories to see how pull and push reported errors.

**Review by Calinou — APPROVED** [review]
Thanks!

**Pull request merged**
