### PR TITLE
Updated to support 4.0.1

### LINKED ISSUE #177: not working in godot 4.0.2 rc1
image

### PR DESCRIPTION
**Pull request by finepointcgi**
This should allow for support for 4.0.1 tested on Windows 11
Fixes #177

### CODE REVIEW

**Review by moonraymurray — APPROVED** [review]

**Review by moonraymurray — APPROVED** [review]

**Comment by Calinou** [comment]
4.0.2 is now released, can you update this PR accordingly?

**Comment by Calinou** [comment]
- See also https://github.com/godotengine/godot/issues/75779.

**Comment by finepointcgi** [comment]
This should be updated to work with 4.0.3

**Comment by Faless** [comment]
This should not be needed, using the extension API of 4.0.0 should work with all 4.0.x versions.

On the other hand, using the extension API for 4.0.3, might end up causing issues in 4.0.0 (the extension API version basically defines the minimum supported version).

For `4.1.x` we will need instead to update as GDExtension broke compatibility one last time to fix some memory issues (see https://github.com/godotengine/godot-cpp/pull/1123).

We should then stop updating at `4.1.0` if we want compatibility with all 4.1+ godot versions.

**Comment by Arakade** [comment]
Tried using with Godot 4.1.1 (Mono) and while it starts, the version control window is blank.
Forgive if this is known -- looking to use Godot with Git for Ludum Dare this weekend but seems 4.1.1 is a no go, right?

**Comment by Calinou** [comment]
- Superseded by https://github.com/godotengine/godot-git-plugin/pull/198. Thanks for the contribution nonetheless!

**Pull request closed without merging**
